### ISSUE TITLE
Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/nextjs-penumbra-client-example#1]
Can't seem to load the example. Do we require consumers to have polyfills installed? or a minimum nodejs version requirement?

```
~/Desktop/nextjs-penumbra-client-example main !1 ?1 ❯ pnpm dev                                                                         ✘ INT  base

> nextjs-penumbra-client-example@0.1.0 dev /Users/gabe/Desktop/nextjs-penumbra-client-example
> next dev --experimental-https

 ⚠ Self-signed certificates are currently an experimental feature, use with caution.
   Attempting to generate self signed certificate. This may prompt for your password
   CA Root certificate created in /Users/gabe/Library/Application Support/mkcert
   Certificates created in /Users/gabe/Desktop/nextjs-penumbra-client-example/certificates
  ▲ Next.js 14.2.3
  - Local:        https://localhost:3000

 ✓ Starting...
 ✓ Ready in 1589ms
 ○ Compiling / ...
 ✓ Compiled / in 1425ms (1033 modules)
 ⨯ TypeError: Promise.withResolvers is not a function
    at eval (./app/components/PraxQueryProvider.tsx:19:102)
    at (ssr)/./app/components/PraxQueryProvider.tsx (/Users/gabe/Desktop/nextjs-penumbra-client-example/.next/server/app/page.js:173:1)
    at Object.__webpack_require__ [as require] (/Users/gabe/Desktop/nextjs-penumbra-client-example/.next/server/webpack-runtime.js:33:42)
digest: "4047804888"
 GET / 500 in 1709ms

```

**Comment by turbocrime** [comment]
closed by https://github.com/penumbra-zone/web/pull/1305 which enabled a minimum node version requirement for the published packages
